//Single user actions
export const USER_REGISTER_ANIMATION = "USER_REGISTER_ANIMATION";
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_ANIMATION = "USER_LOGIN_ANIMATION";
export const RESET_ANIMATIONS = "RESET_ANIMATIONS"
export const USER_LOGOUT = "USER_LOGOUT";
export const SET_ERROR_USER_BACK = "SET_ERROR_USER_BACK";
export const SET_TOKEN = "SET_TOKEN";

//Several users actions
export const GET_ALL_CADETES = "GET_ALL_CADETES";
export const GET_ALL_EMPRESAS = "GET_ALL_EMPRESAS";
export const UPDATE_CADETE = "UPDATE_CADETE";
export const UPDATE_EMPRESA = "UPDATE_EMPRESA";
export const UPDATE_CADETERIA = "UPDATE_CADETERIA";
export const GET_ACCEPTED_CADETERIAS = "GET_ACCEPTED_CADETERIAS";
export const GET_ALL_CADETERIAS = "GET_ALL_CADETERIAS";

//Orders
export const GET_ORDERS = "GET_ORDERS";
export const GET_MY_ORDERS = "GET_MY_ORDERS";
export const GET_ORDER = "GET_ORDER";
export const ADD_ORDERS = "ADD_ORDERS";
export const FILTER_ORDERS = "FILTER_ORDERS";
export const UPDATE_ORDER = "UPDATE_ORDER";
export const UPDATE_SINGLE_ORDER = "UPDATE_SINGLE_ORDER";
export const PICKED_UP = "PICKED_UP";
export const SET_OBSERVACIONES = "SET_OBSERVACIONES"

//Cadeterias
export const SET_MY_TIENDAS = "SET_MY_TIENDAS";
export const SET_MY_CADETERIAS = "SET_MY_CADETERIAS";
export const SET_MY_CADETERIAS_CADETE = "SET_MY_CADETERIAS_CADETE";
export const SET_ALL_CADETERIAS = "SET_ALL_CADETERIAS";
export const ADD_MY_CADETERIA = "ADD_MY_CADETERIA";

//Metricas
export const GET_METRICAS = "GET_METRICAS";


